os: linux             # ОС
sudo: required        # Необходимость прав sudo
language: "minimal"   # Языковой шаблон
services:
  - docker            # Необходимые сервисы
env:
  # Based on Alpine 3.10
  # GCC 8.3
  # CMake 3.14
  # gcovr
  # jscpd
  # valgrind
  # Hunter GTest v1.8.0 (cached)
  # Hunter Boost cached components: exception
  #                                 filesystem
  #                                 log
  #                                 regex
  #                                 system
 - DOCKER_IMAGE=./dockerfiles/dockerfile             # Для использования снять комментарий
 - PATH=/bin/bash:$PATH

before_script:
#  - docker pull $DOCKER_IMAGE                       # Предварительное скачивание образа

jobs:
  include: 
    script:
      - docker build --tag=image -f ./dockerfiles/dockerfile ./dockerfiles
      - docker run --name=image ${PWD}:/project_dir image bash script.sh
      - docker rm -fv dockerfile

before_deploy:
  - sed -i "s/__VERSION__/$TRAVIS_BUILD_NUMBER/g" bintray-descriptor.json

deploy:
  skip_cleanup: true
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
