os: linux 
sudo: required 
language: "minimal"
services:
  - docker 

jobs:
  include: 
    script:
      - docker build --tag=image -f ./dockerfiles/dockerfile ./dockerfiles
      - docker run --name=container -v ${PWD}:/project_dir image bash ./script.sh
      - docker rm -fv container

