os: linux             # ОС
sudo: required        # Необходимость прав sudo
language: "minimal"   # Языковой шаблон
services:
  - docker            # Необходимые сервисы

jobs:
  include: 
    script:
      - docker build --tag=image -f ./dockerfiles/dockerfile ./dockerfiles
      - docker run --name=container -v ${PWD}:/project_dir image bash ./script.sh
      - docker rm -fv container
      - valgrind --tool=memcheck build/Release/shamir_test

before_deploy:
  - sed -i "s/__VERSION__/$TRAVIS_BUILD_NUMBER/g" bintray-descriptor.json

deploy:
  skip_cleanup: true
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
