FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install linux-headers-$(uname -r) \
            musl-dev \
            gcc \
            git \
            g++ \
            make \
            cmake \
            gcovr \
            valgrind \
            perl \
            bash \
            clang -y
    
#Set working directory to mounted project directory
RUN mkdir /project_dir
WORKDIR /project_dir
