FROM alpine:3.10.2

RUN apk update && \
    apk add linux-headers \
            musl-dev \
            build-base \
            gcc \
            git \
            g++ \
            make \
            cmake \
            gcovr \
            valgrind \
            perl \
            bash \
            clang \
            && \
    mkdir -p /tmp/hunter-preload && \
    cd /tmp/hunter-preload && \
    git clone https://github.com/hunter-packages/gate.git gate && \
    cmake -H. -B.build && \
    cd / && \
    rm -rf /tmp/hunter-preload && \
    rm -rf ${HOME}/.cache && \
    rm -rf /var/cache/apk/*
    
#Set working directory to mounted project directory
RUN mkdir /project_dir
WORKDIR /project_dir
