FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install linux-headers \
            musl-dev \
            build-base \
            gcc \
            git \
            g++ \
            make \
            cmake \
            gcovr \
            valgrind \
            perl \
            bash \
            clang 
    
#Set working directory to mounted project directory
RUN mkdir /project_dir
WORKDIR /project_dir
